[general]
import = ["themes/noctalia.toml"]

# Colors (Noctalia Default)

[colors.bright]
black = '#21215F'
blue = '#a9aefe'
cyan = '#9BFECE'
green = '#9BFECE'
magenta = '#FD4663'
red = '#FD4663'
white = '#ffffff'
yellow = '#fff59b'

[colors.cursor]
cursor = '#fff59b'
text = '#070722'

[colors.normal]
black = '#11112d'
blue = '#a9aefe'
cyan = '#9BFECE'
green = '#9BFECE'
magenta = '#FD4663'
red = '#FD4663'
white = '#f3edf7'
yellow = '#fff59b'

[colors.primary]
background = '#070722'
foreground = '#f3edf7'

[colors.selection]
background = '#f3edf7'
text = '#070722'

[window]
decorations = "None"
padding = { x = 12, y = 12 }
opacity = 0.9

[font]
size = 9

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[scrolling]
history = 3023

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "N",       mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]

[terminal]
shell = { program = "/usr/bin/fish" }
