[mgr]
show_hidden = true

[mgr.prepend_keymap]
"g" = "cd ~"
"~" = "cd ~"

[preview]
tab_size = 2

[plugin]

[plugin.preload]

[input]
font_family = "Lilex"
font_size = 16

[select]
font_family = "Lilex"
font_size = 16
